name: Build and Push

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find short code
        id: shortcode
        run: |
          echo "shortref=$(git rev-parse --short HEAD)" >> $SHORTCODE
      - run: echo ${{ env.shortref }}
      - run: docker build . -t $GITHUB_REPOSITORY:${{ env.shortref }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
