name: Build and Push

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        id: tag
        run: git rev-parse --short HEAD
      - run: echo ${{ steps.tag.output }}
      - run: docker build . -t ${{ GITHUB_REPOSITORY }}:${{ steps.tag.output }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
